apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: ordering-api
                port:
                  number: 80